version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes: [db_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mlflow
      MINIO_ROOT_PASSWORD: mlflow123
    volumes: [minio_data:/data]
    ports: ["9000:9000","9001:9001"]

  minio-init:
    image: minio/mc
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c '
        mc alias set local http://minio:9000 mlflow mlflow123 &&
        mc mb local/mlflow || true
      '
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    depends_on: [db, minio]
    ports: ["5050:5000"]
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow@db:5432/mlflow
      MLFLOW_ARTIFACT_ROOT: s3://mlflow
      AWS_ACCESS_KEY_ID: mlflow
      AWS_SECRET_ACCESS_KEY: mlflow123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command:
      [
        "mlflow", "server",
        "--backend-store-uri", "postgresql://mlflow:mlflow@db:5432/mlflow",
        "--default-artifact-root", "s3://mlflow",
        "--host", "0.0.0.0",
        "--port", "5000"
      ]
volumes:
  db_data:
  minio_data:
