mkdir -p .github/workflows
cat > .github/workflows/ci.yml <<'EOF'
name: Iris-MLflow-CI

on: [push, pull_request]

jobs:
  train:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: mlflow
          POSTGRES_PASSWORD: mlflow
          POSTGRES_DB: mlflow
        ports: ['5432:5432']
      minio:
        image: minio/minio:latest
        env:
          MINIO_ROOT_USER: mlflow
          MINIO_ROOT_PASSWORD: mlflow123
        ports: ['9000:9000','9001:9001']
        options: --health-cmd="curl -f http://localhost:9000/minio/health/live" --health-interval=10s --health-retries=5
        command: server /data --console-address ":9001"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}

      - run: pip install -r src/requirements.txt

      - name: Start MLflow server
        run: |
          mlflow server \
            --backend-store-uri postgresql://mlflow:mlflow@localhost:5432/mlflow \
            --default-artifact-root s3://mlflow \
            --host 0.0.0.0 --port 5000 &
          sleep 20      # ждём, пока поднимется

      - name: Create bucket
        run: |
          pip install minio-mc
          mc alias set local http://localhost:9000 mlflow mlflow123
          mc mb --ignore-existing local/mlflow

      - name: Train & log
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
          AWS_ACCESS_KEY_ID: mlflow
          AWS_SECRET_ACCESS_KEY: mlflow123
          MLFLOW_S3_ENDPOINT_URL: http://localhost:9000
        run: python src/train.py --n_estimators 120 --max_depth 6

      - name: Run tests
        run: pytest -q
EOF

