name: Iris-MLflow-CI

on: [push, pull_request]

jobs:
  train:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: mlflow
          POSTGRES_PASSWORD: mlflow
          POSTGRES_DB: mlflow
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: {python-version: '3.11'}

    - run: pip install --quiet -r src/requirements.txt psycopg2-binary

    - name: Start MinIO
      run: |
        sudo docker run -d --name minio \
          -e MINIO_ROOT_USER=mlflow \
          -e MINIO_ROOT_PASSWORD=mlflow123 \
          -p 9000:9000 -p 9001:9001 \
          minio/minio:latest server /data --console-address ":9001"

        for i in {1..15}; do
          curl -sf http://localhost:9000/minio/health/live && break
          echo "waiting MinIO…"; sleep 3
        done

    - name: Create bucket
      run: |
        curl -sSL https://dl.min.io/client/mc/release/linux-amd64/mc -o mc
        chmod +x mc
        ./mc alias set local http://localhost:9000 mlflow mlflow123
        ./mc mb --ignore-existing local/mlflow

    - name: Start MLflow server
      run: |
        python -m pip install mlflow==2.22.0
        mlflow server \
          --backend-store-uri postgresql://mlflow:mlflow@localhost:5432/mlflow \
          --default-artifact-root s3://mlflow \
          --host 0.0.0.0 --port 5000 &
        sleep 15

    - name: Train & log
      env:
        MLFLOW_TRACKING_URI: http://localhost:5000
        AWS_ACCESS_KEY_ID: mlflow
        AWS_SECRET_ACCESS_KEY: mlflow123
        MLFLOW_S3_ENDPOINT_URL: http://localhost:9000
      run: python src/train.py --n_estimators 120 --max_depth 6

    - run: pytest -q
